\documentclass{article}

\begin{document}

<<>>=
library(rstan)
library(ggplot2)
library(shinystan)

dname="gp"

rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())

srv1=read.csv("naes04.csv",header=TRUE)
nrow(srv1)
srv=subset(srv1,!is.na(age) & !is.na(gayFavorStateMarriage) & !is.na(gender) & !is.na(gayKnowSomeone) & !is.na(gayFavorFederalMarriage) & !is.na(race))
nrow(srv)
str(srv)
N_ages<-length(table(srv$age))

#checks
tb1<-table(srv$age,srv$gayFavorStateMarriage)
tb1[1:80,]
tb1[,1]
tb1[,2]

ages     <-18:97
str(ages)
K        <-as.integer(tb1[,1])
str(K)
N        <-as.integer(tb1[,1])+as.integer(tb1[,2])
str(N)

#K_male   <-c( 38, 35, 32, 25, 28, 44, 41, 49, 46, 37, 50, 19, 51, 43, 52, 55, 41, 39, 52, 27)
#N_male   <-c(100, 77, 63, 73, 77,104,114,124, 95, 93,119,112,131,142,162,157,124,128,140,114)
#K_female <-c( 62, 40, 31, 57, 55, 60, 64, 82, 62, 69, 71, 50, 75, 59, 55, 85, 70, 59, 55, 77)
#N_female <-c(100, 76, 65, 99,105,125,115,139,126,151,134,117,164,134,145,178,182,145,144,155)
#K        <-c(100, 76, 63, 82, 83,104,125,132,100,106,121, 89,126,102,107,140,111, 98,107,104)
#N        <-c(200,153,128,172,182,229,229,263,222,249,253,229,295,276,307,335,306,273,292,269)

data.list <- c("N_ages","ages","K","N")
sname<-paste(dname,".stan",sep="")
sname
stanfit <- stan(file=sname, data=data.list,
                      iter=4000, chains=4)
print(stanfit)
fname=paste(dname,"/",dname,"_stanfit_",format(Sys.time(),'%m%d%Y%H%M%S'),".Rdata",sep="")
fname
save(stanfit,file=fname)
@
<<>>=
#launch_shinystan(stanfit)
@


\end{document}